version: '3.8'

services:
  api:
    image: ${DOCKERHUB_USERNAME}/backendv2:latest
    volumes:
      - static:/src/app/static
      - media:/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:12.0-alpine
    env_file: ./backend/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend-build:
    image: ${DOCKERHUB_USERNAME}/reactv2:latest
    volumes:
      - ./frontend/build:/app/build

  nginx:
    image: ${DOCKERHUB_USERNAME}/nginxv2:latest 
    depends_on:
      - frontend-build
    ports:
      - "80:80"

volumes:
  postgres_data:
  static:
  media:
